export const FETCH_BOOK_DATA_REQUEST = "FETCH_BOOK_DATA_REQUEST";
export const FETCH_BOOK_DATA_FALIURE = "FETCH_BOOK_DATA_FALIURE";
export const FETCH_BOOK_DATA_SUCCESS = "FETCH_BOOK_DATA_SUCCESS";

export const FETCH_BOOK_DATA_BY_ID_REQUEST = "FETCH_BOOK_DATA_BY_ID_REQUEST";
export const FETCH_BOOK_DATA_BY_ID_FALIURE = "FETCH_BOOK_DATA_BY_ID_FALIURE";
export const FETCH_BOOK_DATA_BY_ID_SUCCESS = "FETCH_BOOK_DATA_BY_ID_SUCCESS";

export const FETCH_CART_DATA_REQUEST = "FETCH_CART_DATA_REQUEST";
export const FETCH_CART_DATA_FALIURE = "FETCH_CART_DATA_FALIURE";
export const FETCH_CART_DATA_SUCCESS = "FETCH_CART_DATA_SUCCESS";

export const ADD_CART_DATA_REQUEST = "ADD_CART_DATA_REQUEST";
export const ADD_CART_DATA_FALIURE = "ADD_CART_DATA_FALIURE";
export const ADD_CART_DATA_SUCCESS = "ADD_CART_DATA_SUCCESS";

export const UPDATE_CART_DATA_REQUEST = "UPDATE_CART_DATA_REQUEST";
export const UPDATE_CART_DATA_FALIURE = "UPDATE_CART_DATA_FALIURE";
export const UPDATE_CART_DATA_SUCCESS = "UPDATE_CART_DATA_SUCCESS";

export const DELETE_CART_DATA_REQUEST = "DELETE_CART_DATA_REQUEST";
export const DELETE_CART_DATA_FALIURE = "DELETE_CART_DATA_FALIURE";
export const DELETE_CART_DATA_SUCCESS = "DELETE_CART_DATA_SUCCESS";

export const EMPTY_CART_DATA_REQUEST = "EMPTY_CART_DATA_REQUEST";
export const EMPTY_CART_DATA_FALIURE = "EMPTY_CART_DATA_FALIURE";
export const EMPTY_CART_DATA_SUCCESS = "EMPTY_CART_DATA_SUCCESS";